name: Build & Release Aseprite Extension

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Make build.sh executable
        run: chmod +x build.sh

      - name: 🛠 Run build script
        run: ./build.sh

      - name: 🚀 Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.aseprite-extension"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
